inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "bin/**/*"
    - "vendor/**/*"

# Library
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

# Exceptions
# クラス定義のすぐ下のコメント
Style/Documentation:
  Enabled: false
# ruby3以降なので不要
Style/FrozenStringLiteralComment:
  Enabled: false
