inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "bin/**/*"
    - "vendor/**/*"

# Library
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-graphql

# Exceptions
# クラス定義のすぐ下のコメント
Style/Documentation:
  Enabled: false
# ruby3以降なので不要
Style/FrozenStringLiteralComment:
  Enabled: false
# 無理がある
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
# rubocop-graphqlのバグ
#   https://github.com/DmitryTsepelev/rubocop-graphql/issues/47
GraphQL/ExtractInputType:
  Enabled: false
GraphQL/ExtractType:
  Enabled: false
