version: "3.9"
services:
  db:
    image: postgres
    user: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start"
    volumes:
      - .:/duojo
    ports:
      - "3055:3055"
      - "3035:3035"
    depends_on:
      - db
