default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.database[:host] %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  pool: 5

development:
  <<: *default
  database: duojo_development

test:
  <<: *default
  database: duojo_test